#include "team_lut.hpp"

const char* team_lut[33] = {
    "Free Agent",
    "Chicago Bears",
    "Cincinnati Bengals",
    "Buffalo Bills",
    "Denver Broncos",
    "Cleveland Browns",
    "Tampa Bay Buccaneers",
    "Arizona Cardinals",
    "Los Angeles Chargers",
    "Kansas City Chiefs",
    "Indianapolis Colts",
    "Dallas Cowboys",
    "Miami Dolphins",
    "Philadelphia Eagles",
    "Atlanta Falcons",
    "San Francisco 49ers",
    "NY Giants",
    "Jacksonville Jaguars",
    "NY Jets",
    "Detroit Lions",
    "Green Bay Packers",
    "Carolina Panthers",
    "New England Patriots",
    "Las Vegas Raiders",
    "Los Angeles Rams",
    "Baltimore Ravens",
    "Washington Commanders",
    "New Orleans Saints",
    "Seattle Seahawks",
    "Pittsburgh Steelers",
    "Tennessee Titans",
    "Minnesota Vikings",
    "Houston Texans"
};